def compute_readiness(user_states, required_topics):
    """
    Compute overall readiness verdict based on required topics.
    READY: All required topics are at least Intermediate (>=50 mastery), and 50% are Expert (>=80).
    READY WITH GAPS: All required topics are at least Beginner (>=20), but misses full READY criteria.
    NOT YET READY: Any required topic is missing or < 20 mastery.
    """
    if not required_topics:
        return {"status": "NOT YET READY", "missing": [], "score": 0}
        
    state_map = {s.topic_id: s for s in user_states}
    
    missing_competencies = []
    total_mastery = 0
    expert_count = 0
    intermediate_count = 0
    
    for topic in required_topics:
        state = state_map.get(topic)
        if not state or state.mastery_score < 20:
            missing_competencies.append(topic)
        else:
            total_mastery += state.mastery_score
            if state.mastery_score >= 80:
                expert_count += 1
            if state.mastery_score >= 50:
                intermediate_count += 1
                
    avg_score = total_mastery / len(required_topics)
    
    if missing_competencies:
        status = "NOT YET READY"
    elif intermediate_count == len(required_topics) and expert_count >= (len(required_topics) / 2):
        status = "READY"
    else:
        status = "READY WITH GAPS"
        
    return {
        "status": status,
        "missing": missing_competencies,
        "score": int(avg_score),
        "expert_count": expert_count
    }

def generate_readiness_report_md(profile, readiness_data, user_states, role):
    """Generate a markdown report that can be exported."""
    report = f"# Readiness Report: {profile.user_id}\n"
    report += f"**Role:** {role}\n"
    report += f"**Verdict:** {readiness_data['status']}\n"
    report += f"**Overall Readiness Score:** {readiness_data['score']}/100\n\n"
    
    report += "## Competency Matrix\n"
    for state in user_states:
        report += f"- **{state.topic_id}**: {state.difficulty} (Score: {state.mastery_score})\n"
        
    if readiness_data['missing']:
        report += "\n## Missing Competencies (Follow-ups)\n"
        for m in readiness_data['missing']:
            report += f"- Need to complete: {m}\n"
            
    report += "\n---\n*Generated by OnboardIQ Readiness Engine*"
    return report
